name = "StrICU"
desc = "ICU wrapper using the Str package for UTF-16 support"
authors = ["ScottPJones <scottjones@alum.mit.edu>"]
keywords = ["Strings", "ICU", "Encoding", "Regex"]
license = "MIT"
uuid = "124badd8-7747-5df6-9c35-5cbf8cd52816"
version = "1.0.0"

[deps]
Libdl   = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

BinDeps = "9e28174c-4ba2-5203-b857-d8d62c4213ee"

ModuleInterfaceTools = "5cb8414e-7aab-5a03-a681-351269c074bf"
StrBase = "e79e7a6a-7bb1-5a4d-9d64-da657b06f53a" # 2v12uwlr0ueale6n

WinRPM  = "c17dfb99-b4f7-5aad-8812-456da1ad7187"

[extras]
Test    = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "^1.0.0"
ModuleInterfaceTools = "≥ 1.0.0"
StrBase = "≥ 1.0.0"
