name = "StrICU"
desc = "ICU wrapper using the Str package for UTF-16 support"
authors = ["ScottPJones <scottjones@alum.mit.edu>"]
keywords = ["Strings", "ICU", "Encoding", "Regex"]
license = "MIT"
uuid = "62566d7f-c768-4ca3-a8fa-508ab99b922c"

[deps]
Pkg     = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test    = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

BinDeps = "9e28174c-4ba2-5203-b857-d8d62c4213ee"

StrBase = "9ae48233-fac8-48c3-9111-9059e0a096a8" # 2v12uwlr0ueale6n
