name = "StrICU"
desc = "ICU wrapper using the Str package for UTF-16 support"
authors = ["ScottPJones <scottjones@alum.mit.edu>"]
keywords = ["Strings", "ICU", "Encoding", "Regex"]
license = "MIT"
uuid = "62566d7f-c768-4ca3-a8fa-508ab99b922c"
repo = "https://github.com/JuliaString/Strs.jl.git"

[deps]
BinDeps = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
StrBase = "9ae48233-fac8-48c3-9111-9059e0a096a8"
